# Compilers
CC  = /usr/bin/i686-w64-mingw32-gcc

CFLAGS=-g -Wall
#CFLAGS=-O3
 
# Your program name and object files
EXE     = chmayor.exe
OBJECTS = src/chmayor.o
 
# No need to edit anything from here below
 
all: $(EXE)
	# Everything ready!
 
# Linking everything to the executable
$(EXE): $(OBJECTS)
	# Linking...
	$(CC) $(OBJECTS) -o $(EXE)
 
# Compiling all `.cpp` sources
src/%.o: src/%.cpp
	# Compiling $<...
	$(CC) $(CFLAGS) $< -c -o $@
